sudo: required
services:
  - docker

before_install:
  - docker build -t yarina297/docker-complex -f ./client/Dockerfile.dev ./client

script:
  - docker run yarina297/docker-complex npm test -- --coverage

after_success:
  - docker build -t yarina297/multi-client ./client
  - docker build -t yarina297/multi-nginx ./nginx
  - docker build -t yarina297/multi-server ./server
  - docker build -t yarina297/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push yarina297/multi-client
  - docker push yarina297/multi-nginx
  - docker push yarina297/multi-server
  - docker push yarina297/multi-worker
